config/routes.rb
Rails.application.routes.draw do
  resources :delay_tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/delay_task.rb
class DelayTask < ApplicationRecord
  def self.inform(id)
    DelayTask.find(id).inform
  end
  def self.informe
    puts ".................................."
    puts " Start task"
    sleep(10)
    puts " ................................. "
    puts " The task ends here "
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/delay_tasks_controller.rb
class DelayTasksController < ApplicationController
  before_action :set_delay_task, only: [:show, :edit, :update, :destroy]

  # GET /delay_tasks
  # GET /delay_tasks.json
  def index
    @delay_tasks = DelayTask.all
  end

  # GET /delay_tasks/1
  # GET /delay_tasks/1.json
  def show
    @delay_task  = DelayTask.find(params[:id])
  end

  # GET /delay_tasks/new
  def new
    @delay_task = DelayTask.new
  DelayTask.delay(queue: "delaytask",priority:20,run_at: 10.from_now).informe(4)
   flash[:notice] = "doing the background job."
  end

  # GET /delay_tasks/1/edit
  def edit
  end

  # POST /delay_tasks
  # POST /delay_tasks.json
  def create
    @delay_task = DelayTask.create(id: params[:id])


    respond_to do |format|
      if @delay_task.save
        format.html { redirect_to @delay_task, notice: 'Delay task was successfully created.' }
        format.json { render :show, status: :created, location: @delay_task }
      else
        format.html { render :new }
        format.json { render json: @delay_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /delay_tasks/1
  # PATCH/PUT /delay_tasks/1.json
  def update
    respond_to do |format|
      if @delay_task.update(delay_task_params)
        format.html { redirect_to @delay_task, notice: 'Delay task was successfully updated.' }
        format.json { render :show, status: :ok, location: @delay_task }
      else
        format.html { render :edit }
        format.json { render json: @delay_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /delay_tasks/1
  # DELETE /delay_tasks/1.json
  def destroy
    @delay_task.destroy
    respond_to do |format|
      format.html { redirect_to delay_tasks_url, notice: 'Delay task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_delay_task
      @delay_task = DelayTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def delay_task_params
      params.fetch(:delay_task, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/delay_tasks_helper.rb
module DelayTasksHelper
end

app/views/delay_tasks/_form.html.erb
<%= form_with(model: delay_task, local: true) do |form| %>
  <% if delay_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(delay_task.errors.count, "error") %> prohibited this delay_task from being saved:</h2>

      <ul>
      <% delay_task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%=form_for @delay_task do |f|%>
    id: <%= f.text_field :id %><br />
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>



<% end %>

app/views/delay_tasks/edit.html.erb
<h1>Editing Delay Task</h1>

<%= render 'form', delay_task: @delay_task %>

<%= link_to 'Show', @delay_task %> |
<%= link_to 'Back', delay_tasks_path %>

app/views/delay_tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Delay Tasks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @delay_tasks.each do |delay_task| %>
      <tr>
        <td><%= link_to 'Show', delay_task %></td>
        <td><%= link_to 'Edit', edit_delay_task_path(delay_task) %></td>
        <td><%= link_to 'Destroy', delay_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Delay Task', new_delay_task_path %>

app/views/delay_tasks/new.html.erb
<h1>New Delay Task</h1>

<%= render 'form', delay_task: @delay_task %>

<%= link_to 'Back', delay_tasks_path %>

app/views/delay_tasks/show.html.erb
<p id="notice"><%= notice %></p>
<h1> Id current delay task is </h1>
<p> <%=  @delay_task.id%></p>
<%= link_to 'Edit', edit_delay_task_path(@delay_task) %> |
<%= link_to 'Back', delay_tasks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BackGroundJobs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>